
export const TeamLogos = {
    "Atlanta Hawks": require("@/assets/images/teamLogos/AtlantaHawksLogo.png"),
    "Boston Celtics": require("@/assets/images/teamLogos/BostonCelticsLogo.png"),
    "Brooklyn Nets": require("@/assets/images/teamLogos/BrooklynNetsLogo.png"),
    "Charlotte Hornets": require("@/assets/images/teamLogos/CharlotteHornetsLogo.png"),
    "Chicago Bulls": require("@/assets/images/teamLogos/ChicagoBullsLogo.png"),
    "Cleveland Cavaliers": require("@/assets/images/teamLogos/ClevelandCavaliersLogo.png"),
    "Dallas Mavericks": require("@/assets/images/teamLogos/DallasMavericksLogo.png"),
    "Denver Nuggets": require("@/assets/images/teamLogos/DenverNuggetsLogo.png"),
    "Detroit Pistons": require("@/assets/images/teamLogos/DetroitPistonsLogo.png"),
    "Golden State Warriors": require("@/assets/images/teamLogos/GoldenStateWarriorsLogo.png"),
    "Houston Rockets": require("@/assets/images/teamLogos/HoustonRocketsLogo.png"),
    "Indiana Pacers": require("@/assets/images/teamLogos/IndianaPacersLogo.png"),
    "LA Clippers": require("@/assets/images/teamLogos/LAClippersLogo.png"),
    "Los Angeles Lakers": require("@/assets/images/teamLogos/LosAngelesLakersLogo.png"),
    "Memphis Grizzlies": require("@/assets/images/teamLogos/MemphisGrizzliesLogo.png"),
    "Miami Heat": require("@/assets/images/teamLogos/MiamiHeatLogo.png"),
    "Milwaukee Bucks": require("@/assets/images/teamLogos/MilwaukeeBucksLogo.png"),
    "Minnesota Timberwolves": require("@/assets/images/teamLogos/MinnesotaTimberwolvesLogo.png"),
    "New Orleans Pelicans": require("@/assets/images/teamLogos/NewOrleansPelicansLogo.png"),
    "New York Knicks": require("@/assets/images/teamLogos/NewYorkKnicksLogo.png"),
    "Oklahoma City Thunder": require("@/assets/images/teamLogos/OklahomaCityThunderLogo.png"),
    "Orlando Magic": require("@/assets/images/teamLogos/OrlandoMagicLogo.png"),
    "Philadelphia 76ers": require("@/assets/images/teamLogos/Philadelphia76ersLogo.png"),
    "Phoenix Suns": require("@/assets/images/teamLogos/PhoenixSunsLogo.png"),
    "Portland Trail Blazers": require("@/assets/images/teamLogos/PortlandTrailblazersLogo.png"),
    "Sacramento Kings": require("@/assets/images/teamLogos/SacramentoKingsLogo.png"),
    "San Antonio Spurs": require("@/assets/images/teamLogos/SanAntonioSpursLogo.png"),
    "Toronto Raptors": require("@/assets/images/teamLogos/TorontoRaptorsLogo.png"),
    "Utah Jazz": require("@/assets/images/teamLogos/UtahJazzLogo.png"),
    "Washington Wizards": require("@/assets/images/teamLogos/WashingtonWizardsLogo.png"),
  };